### PR TITLE
2.0

### LINKED ISSUE #45: pg dependency
`pg-pool` requires `pg` but does not include it in either `dependencies` or `peerDependencies`

### LINKED ISSUE #56: drop support of node <4 ?
Currently travis failed on node 0.10 and 0.12 because module standard.js only supports node >=4 because of eslint >=3.

I think it will be ok to drop support of node <4, once pg will also remove support, see https://github.com/brianc/node-postgres/issues/1298

### LINKED ISSUE #58: Fails to reconnect after invoking end()
We call `end()` on the pool in order to shut down all the connections within the pool.

However, doing so prevents us from being able to use the object any longer.

Any attempt of calling `.connect` after `.end()` was called once results in the following error:

```
pool is draining and cannot accept work
```

Below is a complete test application:

```js
'use strict';

var pg = require('pg');

var config = {
    database: 'newone',
    port: 5433,
    user: 'postgres'
};

var pool = new pg.Pool(config);

function test1() {
    pool.connect((err, client, done) => {
        if (err) {
            console.log('Error Connecting:', err);
            return;
        }
        client.query('select count(*) from users', (err, data) => {
            if (err) {
                console.log('Query Error:', err);
            } else {
                console.log('DATA:', data.rows);
            }
            done();
            pool.end();
            test2();
        });
    });
}

function test2() {
    pool.connect((err, client, done) => {
        if (err) {
            console.log('Error Connecting:', err);
            return;
        }
        client.query('select count(*) from users', (err, data) => {
            if (err) {
                console.log('Query Error:', err);
            } else {
                console.log('DATA:', data.rows);
            }
            done();
            pool.end();
        });
    });
}

test1();
```

`test1` ends successfully, but in `test2` it always throws that error on this line:

```js
console.log('Error Connecting:', err);
//=> pool is draining and cannot accept work
```

### LINKED ISSUE #64: Does idleTimeoutMillis = -1 keep connections open indefinently
Does `idleTimeoutMillis = -1` keep connections open indefinitely or cause them to close immediately? Reading the ops of [node-poo]l[1] led me to believe the connection would just stay open but this doesn't seem to be the case.

[1]:https://github.com/coopernurse/node-pool#documentation

### PR DESCRIPTION
**Pull request by brianc**
This contains a massive number of internal changes. However, the external API remains very close to the same.

The breaking changes are:

- Drop support for node < 4.x. closes #56
- No longer use [node-pool](https://github.com/coopernurse/node-pool) as a dependency so any configuration options you previously passed to node-pool will not work anymore except for `max` and `idleTimeoutMillis`
- Cannot call pool constructor without `new` keyword

I attempted to upgrade to node-pool@3.x, but it weirdly no longer supports returning an error when a client fails to connect.  Instead it tries to reconnect the client in a tight loop and [makes the error non-actionable](https://github.com/coopernurse/node-pool/blob/master/test/generic-pool-test.js#L274). I was unable to find a good way to hook into this behavior and override it. Furthermore it has a lot of additional bells and whistles for priority queuing, min levels, auto-connection, and other behavior pg and pg-pool have never used.  Initially I was distraught at the thought of implementing the pooling behavior here, but it turns out it wasn't very much code & all the tests still pass!

After this I spent some time going through and writing tests for many of the open issues to verify they no longer happen.  I also added support for the long requested `connectionTimeoutMillis` - now supplying `connectionTimeoutMillis` as a millisecond value will cause the pool to return an error on your `connect` call if a connection could not be established within the configured time.  By default there is no timeout.

Known fixes:
- Destroyed workers are always recreated without the previous workarounds for node-pool
- `pg>=5.0` is a `peerDependency`. closes #45
- added `.ending` property which will allow you to inspect when the pool is in the process of shutting down. closes #58
- ensure `idleTimeoutMillis` of 0 disables idle timeout. closes #64

### CODE REVIEW

File: index.js [hunk 1]
```diff
@@ -1,174 +1,255 @@
...
+    this._pendingQueue.push((err, client) => {
       if (err) {
-        this.log('acquire client. error:', err)
-        if (cb) {
-          cb(err, null, function () {})
-        } else {
-          reject(err)
-        }
-        return
+        return cb(err, undefined, function () { })
```
Comment (calebboyd) [inline index.js]: I think this block is unreachable based on the use of _pendingQueue

File: index.js [hunk 2]
```diff
@@ -1,174 +1,255 @@
...
-  return this._promise(cb, function (resolve, reject) {
-    this.pool.drain(function () {
-      this.log('pool drained, calling destroy all now')
-      this.pool.destroyAllNow(resolve)
-    }.bind(this))
-  }.bind(this))
+  this.log('ending')
+  if (this.ending) {
+    const err = new Error('Called end on pool more than once')
+    return cb ? cb(err) : this.Promise.reject(err)
```
Comment (calebboyd) [inline index.js]: sync : async

File: index.js [hunk 3]
```diff
@@ -1,174 +1,255 @@
...
+  }
+  this.ending = true
+  const promised = this._promisify(cb)
+  this._endCallback = promised.callback
+  this._pulseQueue()
+  return promised.result
 }
+
+Object.defineProperty(Pool.prototype, 'waitingCount', {
```
Comment (calebboyd) [inline index.js]: Could clean this up a lot if the export was switched to something like:
```javacript
module.exports = function (options, client) {
    return new PgPool(options, client)
}
```

File: index.js [hunk 4]
```diff
@@ -1,174 +1,255 @@
...
-    this.pool.acquire(function (err, client) {
+  if (this.ending) {
+    const err = new Error('Cannot use a pool after calling end on the pool')
+    return cb ? cb(err) : this.Promise.reject(err)
+  }
+  if (this._clients.length >= this.options.max || this._idle.length) {
+    const response = this._promisify(cb)
+    const result = response.result
+    cb = response.callback
+    this._pendingQueue.push((err, client) => {
```
Comment (calebboyd) [inline index.js]: proposal: instead of  handling this in a closure -- just store the waiter and handle this when invoking it during dequeue/shift

File: .travis.yml [hunk 5]
```diff
@@ -8,6 +8,3 @@ matrix:
     - node_js: "6"
       addons:
         postgresql: "9.4"
-    - node_js: "8"
```
Comment (abenhamdine) [inline .travis.yml]: Just wonder : why remove node 8 ?

**Comment by brianc** [comment]
Thank you so much for the feedback and review! I'm not _quite_ done w/ this branch yet - code's still a bit dirty...but have quite a bit of client work in the next few days so I'll take me a bit of time to get to this.  But know I'm grateful & I'll be back within a day or two! :dancer:

File: .travis.yml (hunk 5 above)
Comment (brianc) [inline .travis.yml]: it was messing up in travis but working locally even though the same tests were passing locally - I just removed it temporarily so I could make sure the other tests were passing.  I'll need to get it working in travis eventually.

File: test/bring-your-own-promise.js [hunk 6]
```diff
@@ -0,0 +1,36 @@
+'use strict'
+const co = require('co')
+const expect = require('expect.js')
+
+const describe = require('mocha').describe
+const it = require('mocha').it
+const BluebirdPromise = require('bluebird')
```
Comment (brianc) [inline test/bring-your-own-promise.js]: nice! today I learned!

File: index.js (hunk 3 above)
Comment (brianc) [inline index.js]: I'm not following how this would be cleaned up?  Could you expand on what you meant here?

File: index.js (hunk 2 above)
Comment (brianc) [inline index.js]: Is it bad to do sync if its a callback and async if it's a promise? Promises are always async, but callbacks done necessarily have to be and AFAIK there's never been an idiom saying they should be.

File: index.js (hunk 4 above)
Comment (brianc) [inline index.js]: excellent suggestion! cleaned this up.

File: index.js [hunk 7]
```diff
@@ -1,174 +1,255 @@
...
+
+  if (this.ending) {
+    this._remove(client)
+  } else {
+    this._idle.push(new IdleItem(client, tid))
+  }
+  this._pulseQueue()
 }
 
 Pool.prototype.connect = function (cb) {
```
Comment (brianc) [inline index.js]: Is that bad?  It's a semver major bump & I'd _rather_ not introduce a `nextTick` just to keep it async.

File: index.js [hunk 8]
```diff
@@ -1,174 +1,255 @@
...
+}
 
-  client.on('error', function (e) {
-    this.log('connected client error:', e)
-    this.pool.destroy(client)
-    e.client = client
-    this.emit('error', e, client)
-  }.bind(this))
+function release (client, err) {
+  client.release = function () { throw new Error('called release twice') }
```
Comment (brianc) [inline index.js]: good call. done.

**Comment by brianc** [comment]
> I did notice that promise support is still a bit second class. In that -- promisified apis would be able to perform much better than the scheme currently used.

@calebboyd - using callbacks _internally_ in this module is so we can support `pg>=5.x` instead of `pg@7` which is when all the APIs for `pg` are fully promisified.  What do you mean by that exactly - could you elaborate?

File: index.js (hunk 3 above)
Comment (calebboyd) [inline index.js]: np, I just mean taking advantage of the class sugar for function defs and getters of the new min node version =)

````javascript
class PgPool {
  _isFull() {..}
  ...
  connect() {...}
  ...  
  get waitingCount() {...}
  get totalCount() {...}
  get idleCount() {...}
}

module.exports = function (options, client) {
   return new PgPool(options, client)
}
```

File: index.js (hunk 2 above)
Comment (calebboyd) [inline index.js]: In general, Its not good to mix async and sync in the same API. Whats weird here is nothing invoked internally is actually async except the result. In one case I can get the error synchronously (looks async) and the other, async.

If I were to express a preference it would be to stick with an async api throughout.

Here is a tree of posts that go into a lot more detail http://blog.izs.me/post/59142742143/designing-apis-for-asynchrony

**Comment by calebboyd** [comment]
Mostly I think that it would be best to stick with one API or the other. 
My reasoning is that: accepting a custom Promise at this level would cut into performance. 

For example, `Bluebird.promisify`, will rewrite the function (emit new code) in order to maintain low overhead when allocating `new Promise`s -- and then uses an internal implementation. Node's `require('util').promisify`  will use a native deferred api. Each of which would behave much faster than creating the `new Promise` and deferred mechanism being used. As a plus, plain callbacks for waiters in this internal queue will be always the quicker solution of the two.

In general sticking with callbacks here will allow people who use promises (I'm one) to do so with the lowest overhead, which is a plus for the library that proxies queries.

**Comment by calebboyd** [comment]
I guess that wasn't super clear. I don't have anything that would stop me from using this (I could promisify it anyways to avoid the issue). But Maybe the removal of `this.Promise` such that `promisify` is encouraged instead. As that is generally blessed now (in node core)

File: index.js (hunk 2 above)
Comment (brianc) [inline index.js]: Good point - I'll fix this

File: index.js (hunk 3 above)
Comment (brianc) [inline index.js]: I'll try that & see if it works in node 4. If so, definitely will go this way.

**Comment by brianc** [comment]
I'll take a look at hard look at the code once I finish it to ensure it's not doing unnecessary work wrt allocating promises.  It should only allocate a promise if you __don't__ supply a callback: if you use a callback it will never even allocate any promises so you don't have to be concerned about any performance as some folks who use callbacks tend to be. 🙅 

As far as `Bluebird.promsify` versus the ability to accept a callback or return a promise (the api that this lib is going for) - I'd be pretty surprised if `Bluebird.promsify` generates any noticeable performance gains over what's going on in this code, but I'll investigate that to see...and like you said if someone prefers that approach nothing is stopping them from doing that as well in their own code on top of the pool. 👍 

The goal is to support both promises and callbacks in a transparent way versus requiring someone run `Bluebird.promsify` or something similar on the pool, at least for the time being: supply a callback & callbacks will be used. Don't & you'll get a promise back. 😄 

Thanks again for the feedback & comments.  They're very helpful! 👏

**Comment by calebboyd** [comment]
Thank you for entertaining them. I'm very grateful for your work on these tools  🔨
